import java.lang.*;
import java.util.*;
import java.io.*;

class CatchMultipleException {
	public static void main(String args[]) {
		int num1, num2;
		int arr[] = new int[10];
		Scanner sc = new Scanner(System.in);
		try {
			/*Take values for numerator and denominator from the console */
			System.out.print("Enter a value for numerator: ");
			num1=sc.nextInt();
			System.out.print("Enter a value for denominator: ");
			num2=sc.nextInt();
			
			
			arr[10] = num1/num2;/* Divide the numerator and denominator*/ ;
		} 
		
		catch(ArithmeticException ae) {
			System.out.println("Exception caught: "+ae.getMessage());
		}
		catch(ArrayIndexOutOfBoundsException ai) {
			System.out.println("Exception caught: "+ai.getMessage());
		}/* catech ArithmeticException and ArrayIndexOutOfBoundsException here*/
	}
}